In [1]:
import pandas as pd
df =pd.read_csv(r"C:\Users\"user"\Downloads\customer_shopping_behavior.csv")

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [4]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [5]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [9]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ',"_")
df=df.rename(columns={"purchase_amount_(usd)":"purchase_amount"})

In [10]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [11]:
labels=["young_adult","adult","middle_aged","senior"]
df["age_group"]=pd.qcut(df['age'],q=4,labels=labels)

In [12]:
df[["age","age_group"]].head(10)

   age    age_group
0   55  middle_aged
1   19  young_adult
2   50  middle_aged
3   21  young_adult
4   45  middle_aged
5   46  middle_aged
6   63       senior
7   27  young_adult
8   26  young_adult
9   57  middle_aged

In [13]:
frequency_mapping={
    "Fortnightly":14,
    "Weekly":7,
    "Monthly":30,
    "Quarterly":90,
    "Annualy":365,
    "Bi_Weekly":14,
    "Every 3 Months":90
}
df["Purchase_frequency_days"]=df["frequency_of_purchases"].map(frequency_mapping)

In [14]:
df[["Purchase_frequency_days","frequency_of_purchases"]].head(10)

   Purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                      NaN               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                      NaN               Annually
9                     90.0              Quarterly

In [15]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [16]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [17]:
df=df.drop('promo_code_used',axis=1)

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'Purchase_frequency_days'],
      dtype='str')

In [19]:
%load_ext sql
%sql mysql+pymysql://root:"your_password"@localhost:3306/sys

In [20]:
%%sql
show databases;

 * mysql+pymysql://root:***@localhost:3306/sys
9 rows affected.

[('autotrack360',),
 ('customer_behaviour',),
 ('information_schema',),
 ('mysql',),
 ('performance_schema',),
 ('sakila',),
 ('sql_lessons',),
 ('sys',),
 ('world',)]

In [21]:
%%sql
create database customer_behaviour;

 * mysql+pymysql://root:***@localhost:3306/sys
(pymysql.err.ProgrammingError) (1007, "Can't create database 'customer_behaviour'; database exists")
[SQL: create database customer_behaviour;]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [22]:
%%sql 
show databases;

 * mysql+pymysql://root:***@localhost:3306/sys
9 rows affected.

[('autotrack360',),
 ('customer_behaviour',),
 ('information_schema',),
 ('mysql',),
 ('performance_schema',),
 ('sakila',),
 ('sql_lessons',),
 ('sys',),
 ('world',)]

In [23]:
%%sql
use customer_behaviour;

 * mysql+pymysql://root:***@localhost:3306/sys
0 rows affected.

[]

In [24]:
%%sql
show tables;

 * mysql+pymysql://root:***@localhost:3306/sys
1 rows affected.

[('customer_data',)]

In [25]:
from sqlalchemy import create_engine

username="root"
passsword="your_password"
host="localhost"
port="3306"
database="customer_behaviour"

engine = create_engine(f"mysql+pymysql://root:"your_password"@localhost:3306/customer_behaviour")

table_name="customer_data"
df.to_sql(table_name,engine,if_exists="replace",index=False)

3900

In [26]:
%%sql
select * from customer_data;

 * mysql+pymysql://root:***@localhost:3306/sys
3900 rows affected.

[(1, 55, 'Male', 'Blouse', 'Clothing', 53, 'Kentucky', 'L', 'Gray', 'Winter', 3.1, 'Yes', 'Express', 'Yes', 14, 'Venmo', 'Fortnightly', 'middle_aged', 14.0),
 (2, 19, 'Male', 'Sweater', 'Clothing', 64, 'Maine', 'L', 'Maroon', 'Winter', 3.1, 'Yes', 'Express', 'Yes', 2, 'Cash', 'Fortnightly', 'young_adult', 14.0),
 (3, 50, 'Male', 'Jeans', 'Clothing', 73, 'Massachusetts', 'S', 'Maroon', 'Spring', 3.1, 'Yes', 'Free Shipping', 'Yes', 23, 'Credit Card', 'Weekly', 'middle_aged', 7.0),
 (4, 21, 'Male', 'Sandals', 'Footwear', 90, 'Rhode Island', 'M', 'Maroon', 'Spring', 3.5, 'Yes', 'Next Day Air', 'Yes', 49, 'PayPal', 'Weekly', 'young_adult', 7.0),
 (5, 45, 'Male', 'Blouse', 'Clothing', 49, 'Oregon', 'M', 'Turquoise', 'Spring', 2.7, 'Yes', 'Free Shipping', 'Yes', 31, 'PayPal', 'Annually', 'middle_aged', None),
 (6, 46, 'Male', 'Sneakers', 'Footwear', 20, 'Wyoming', 'M', 'White', 'Summer', 2.9, 'Yes', 'Standard', 'Yes', 14, 'Venmo', 'Weekly', 'middle_aged', 7.0),
 (7, 63, 'Male', 'Shirt', 'Clothing', 85, 'Montana', 'M', 'Gray', 'Fall', 3.2, 'Yes', 'Free Shipping', 'Yes', 49, 'Cash', 'Quarterly', 'senior', 90.0),
 (8, 27, 'Male', 'Shorts', 'Clothing', 34, 'Louisiana', 'L', 'Charcoal', 'Winter', 3.2, 'Yes', 'Free Shipping', 'Yes', 19, 'Credit Card', 'Weekly', 'young_adult', 7.0),
 (9, 26, 'Male', 'Coat', 'Outerwear', 97, 'West Virginia', 'L', 'Silver', 'Summer', 2.6, 'Yes', 'Express', 'Yes', 8, 'Venmo', 'Annually', 'young_adult', None),
 (10, 57, 'Male', 'Handbag', 'Accessories', 31, 'Missouri', 'M', 'Pink', 'Spring', 4.8, 'Yes', '2-Day Shipping', 'Yes', 4, 'Cash', 'Quarterly', 'middle_aged', 90.0),
 (11, 53, 'Male', 'Shoes', 'Footwear', 34, 'Arkansas', 'L', 'Purple', 'Fall', 4.1, 'Yes', 'Store Pickup', 'Yes', 26, 'Bank Transfer', 'Bi-Weekly', 'middle_aged', None),
 (12, 30, 'Male', 'Shorts', 'Clothing', 68, 'Hawaii', 'S', 'Olive', 'Winter', 4.9, 'Yes', 'Store Pickup', 'Yes', 10, 'Bank Transfer', 'Fortnightly', 'young_adult', 14.0),
 (13, 61, 'Male', 'Coat', 'Outerwear', 72, 'Delaware', 'M', 'Gold', 'Winter', 4.5, 'Yes', 'Express', 'Yes', 37, 'Venmo', 'Fortnightly', 'senior', 14.0),
 (14, 65, 'Male', 'Dress', 'Clothing', 51, 'New Hampshire', 'M', 'Violet', 'Spring', 4.7, 'Yes', 'Express', 'Yes', 31, 'PayPal', 'Weekly', 'senior', 7.0),
 (15, 64, 'Male', 'Coat', 'Outerwear', 53, 'New York', 'L', 'Teal', 'Winter', 4.7, 'Yes', 'Free Shipping', 'Yes', 34, 'Debit Card', 'Weekly', 'senior', 7.0),
 (16, 64, 'Male', 'Skirt', 'Clothing', 81, 'Rhode Island', 'M', 'Teal', 'Winter', 2.8, 'Yes', 'Store Pickup', 'Yes', 8, 'PayPal', 'Monthly', 'senior', 30.0),
 (17, 25, 'Male', 'Sunglasses', 'Accessories', 36, 'Alabama', 'S', 'Gray', 'Spring', 4.1, 'Yes', 'Next Day Air', 'Yes', 44, 'Debit Card', 'Bi-Weekly', 'young_adult', None),
 (18, 53, 'Male', 'Dress', 'Clothing', 38, 'Mississippi', 'XL', 'Lavender', 'Winter', 4.7, 'Yes', '2-Day Shipping', 'Yes', 36, 'Venmo', 'Quarterly', 'middle_aged', 90.0),
 (19, 52, 'Male', 'Sweater', 'Clothing', 48, 'Montana', 'S', 'Black', 'Summer', 4.6, 'Yes', 'Free Shipping', 'Yes', 17, 'Cash', 'Weekly', 'middle_aged', 7.0),
 (20, 66, 'Male', 'Pants', 'Clothing', 90, 'Rhode Island', 'M', 'Green', 'Summer', 3.3, 'Yes', 'Standard', 'Yes', 46, 'Debit Card', 'Bi-Weekly', 'senior', None),
 (21, 21, 'Male', 'Pants', 'Clothing', 51, 'Louisiana', 'M', 'Black', 'Winter', 2.8, 'Yes', 'Express', 'Yes', 50, 'Cash', 'Every 3 Months', 'young_adult', 90.0),
 (22, 31, 'Male', 'Pants', 'Clothing', 62, 'North Carolina', 'M', 'Charcoal', 'Winter', 4.1, 'Yes', 'Store Pickup', 'Yes', 22, 'Debit Card', 'Quarterly', 'young_adult', 90.0),
 (23, 56, 'Male', 'Pants', 'Clothing', 37, 'California', 'M', 'Peach', 'Summer', 3.2, 'Yes', 'Store Pickup', 'Yes', 32, 'Debit Card', 'Annually', 'middle_aged', None),
 (24, 31, 'Male', 'Pants', 'Clothing', 88, 'Oklahoma', 'XL', 'White', 'Winter', 4.4, 'Yes', 'Express', 'Yes', 40, 'Credit Card', 'Weekly', 'young_adult', 7.0),
 (25, 18, 'Male', 'Jacket', 'Outerwear', 22, 'Florida', 'M', 'Green', 'Fall', 2.9, 'Yes', 'Store Pickup', 'Yes', 16, 'Debit Card', 'Weekly', 'young_adult', 7.0),
 (26, 18, 'Male', 'Hoodie', 'Clothing', 25, 'Texas', 'M', 'Silver', 'Summer', 3.6, 'Yes', 'Express', 'Yes', 14, 'PayPal', 'Annually', 'young_adult', None),
 (27, 38, 'Male', 'Jewelry', 'Accessories', 20, 'Nevada', 'M', 'Red', 'Spring', 3.6, 'Yes', 'Next Day Air', 'Yes', 13, 'Credit Card', 'Annually', 'adult', None),
 (28, 56, 'Male', 'Shorts', 'Clothing', 56, 'Kentucky', 'L', 'Cyan', 'Summer', 5.0, 'Yes', 'Next Day Air', 'Yes', 7, 'Bank Transfer', 'Every 3 Months', 'middle_aged', 90.0),
 (29, 54, 'Male', 'Handbag', 'Accessories', 94, 'North Carolina', 'M', 'Gray', 'Fall', 4.4, 'Yes', 'Free Shipping', 'Yes', 41, 'PayPal', 'Every 3 Months', 'middle_aged', 90.0),
 (30, 31, 'Male', 'Dress', 'Clothing', 48, 'Wyoming', 'S', 'Black', 'Fall', 4.1, 'Yes', 'Store Pickup', 'Yes', 14, 'Credit Card', 'Weekly', 'young_adult', 7.0),
 (31, 57, 'Male', 'Jewelry', 'Accessories', 31, 'North Carolina', 'L', 'Black', 'Winter', 4.7, 'Yes', 'Standard', 'Yes', 16, 'Credit Card', 'Monthly', 'middle_aged', 30.0),
 (32, 33, 'Male', 'Dress', 'Clothing', 79, 'West Virginia', 'L', 'Brown', 'Winter', 4.7, 'Yes', 'Store Pickup', 'Yes', 45, 'Venmo', 'Monthly', 'adult', 30.0),
 (33, 36, 'Male', 'Jacket', 'Outerwear', 67, 'Kansas', 'M', 'Silver', 'Summer', 4.9, 'Yes', 'Free Shipping', 'Yes', 37, 'Venmo', 'Annually', 'adult', None),
 (34, 54, 'Male', 'Pants', 'Clothing', 38, 'Colorado', 'L', 'Green', 'Summer', 3.3, 'Yes', 'Store Pickup', 'Yes', 45, 'Cash', 'Quarterly', 'middle_aged', 90.0),
 (35, 36, 'Male', 'T-shirt', 'Clothing', 91, 'North Dakota', 'L', 'Violet', 'Spring', 4.6, 'Yes', '2-Day Shipping', 'Yes', 38, 'PayPal', 'Quarterly', 'adult', 90.0),
 (36, 54, 'Male', 'Blouse', 'Clothing', 33, 'Massachusetts', 'M', 'Cyan', 'Summer', 4.0, 'Yes', '2-Day Shipping', 'Yes', 48, 'Credit Card', 'Bi-Weekly', 'middle_aged', None),
 (37, 35, 'Male', 'T-shirt', 'Clothing', 69, 'Illinois', 'M', 'Maroon', 'Winter', 4.6, 'Yes', 'Free Shipping', 'Yes', 44, 'PayPal', 'Fortnightly', 'adult', 14.0),
 (38, 35, 'Male', 'Jeans', 'Clothing', 45, 'Indiana', 'S', 'Cyan', 'Summer', 2.8, 'Yes', 'Store Pickup', 'Yes', 10, 'PayPal', 'Weekly', 'adult', 7.0),
 (39, 29, 'Male', 'Dress', 'Clothing', 37, 'Florida', 'M', 'Red', 'Winter', 3.7, 'Yes', '2-Day Shipping', 'Yes', 44, 'Venmo', 'Every 3 Months', 'young_adult', 90.0),
 (40, 70, 'Male', 'Pants', 'Clothing', 60, 'Arizona', 'S', 'Turquoise', 'Summer', 4.2, 'Yes', 'Express', 'Yes', 18, 'Credit Card', 'Monthly', 'senior', 30.0),
 (41, 69, 'Male', 'Handbag', 'Accessories', 76, 'Louisiana', 'L', 'Beige', 'Winter', 4.6, 'Yes', 'Next Day Air', 'Yes', 31, 'Debit Card', 'Quarterly', 'senior', 90.0),
 (42, 67, 'Male', 'Scarf', 'Accessories', 39, 'Alaska', 'M', 'Orange', 'Spring', 4.5, 'Yes', 'Standard', 'Yes', 40, 'Venmo', 'Annually', 'senior', None),
 (43, 20, 'Male', 'Coat', 'Outerwear', 100, 'Tennessee', 'M', 'Beige', 'Spring', 4.1, 'Yes', 'Free Shipping', 'Yes', 15, 'PayPal', 'Annually', 'young_adult', None),
 (44, 25, 'Male', 'Scarf', 'Accessories', 69, 'Ohio', 'L', 'Lavender', 'Fall', 3.7, 'Yes', 'Store Pickup', 'Yes', 19, 'PayPal', 'Fortnightly', 'young_adult', 14.0),
 (45, 39, 'Male', 'Hat', 'Accessories', 53, 'Kentucky', 'S', 'Silver', 'Summer', 4.6, 'Yes', 'Free Shipping', 'Yes', 45, 'PayPal', 'Weekly', 'adult', 7.0),
 (46, 50, 'Male', 'Socks', 'Clothing', 21, 'Tennessee', 'XL', 'Indigo', 'Fall', 2.9, 'Yes', '2-Day Shipping', 'Yes', 25, 'PayPal', 'Annually', 'middle_aged', None),
 (47, 57, 'Male', 'Shirt', 'Clothing', 43, 'California', 'L', 'White', 'Summer', 2.9, 'Yes', 'Store Pickup', 'Yes', 45, 'Cash', 'Quarterly', 'middle_aged', 90.0),
 (48, 55, 'Male', 'Jewelry', 'Accessories', 54, 'Montana', 'M', 'Charcoal', 'Winter', 4.5, 'Yes', 'Free Shipping', 'Yes', 36, 'Cash', 'Weekly', 'middle_aged', 7.0),
 (49, 42, 'Male', 'Shirt', 'Clothing', 55, 'Nevada', 'M', 'Orange', 'Summer', 2.7, 'Yes', 'Store Pickup', 'Yes', 38, 'Cash', 'Monthly', 'adult', 30.0),
 (50, 68, 'Male', 'Hoodie', 'Clothing', 30, 'New Jersey', 'S', 'Indigo', 'Spring', 4.6, 'Yes', 'Next Day Air', 'Yes', 34, 'Debit Card', 'Bi-Weekly', 'senior', None),
 (51, 49, 'Male', 'Blouse', 'Clothing', 28, 'Maryland', 'M', 'Red', 'Spring', 3.7, 'Yes', 'Store Pickup', 'Yes', 39, 'Debit Card', 'Bi-Weekly', 'middle_aged', None),
 (52, 59, 'Male', 'Skirt', 'Clothing', 59, 'Vermont', 'XL', 'Gray', 'Winter', 4.7, 'Yes', '2-Day Shipping', 'Yes', 7, 'Credit Card', 'Quarterly', 'senior', 90.0),
 (53, 42, 'Male', 'T-shirt', 'Clothing', 20, 'Alaska', 'M', 'Green', 'Summer', 2.6, 'Yes', 'Free Shipping', 'Yes', 26, 'Credit Card', 'Weekly', 'adult', 7.0),
 (54, 29, 'Male', 'Skirt', 'Clothing', 24, 'Mississippi', 'S', 'Peach', 'Winter', 3.9, 'Yes', 'Next Day Air', 'Yes', 35, 'Credit Card', 'Weekly', 'young_adult', 7.0),
 (55, 47, 'Male', 'Coat', 'Outerwear', 94, 'New Mexico', 'M', 'Brown', 'Summer', 4.2, 'Yes', 'Next Day Air', 'Yes', 35, 'Debit Card', 'Bi-Weekly', 'middle_aged', None),
 (56, 40, 'Male', 'Jacket', 'Outerwear', 28, 'South Carolina', 'M', 'Lavender', 'Winter', 3.0, 'Yes', '2-Day Shipping', 'Yes', 49, 'Credit Card', 'Annually', 'adult', None),
 (57, 41, 'Male', 'Backpack', 'Accessories', 73, 'Mississippi', 'XL', 'Brown', 'Summer', 4.7, 'Yes', 'Store Pickup', 'Yes', 46, 'Credit Card', 'Weekly', 'adult', 7.0),
 (58, 21, 'Male', 'Coat', 'Outerwear', 64, 'West Virginia', 'M', 'White', 'Summer', 4.4, 'Yes', 'Store Pickup', 'Yes', 17, 'Debit Card', 'Fortnightly', 'young_adult', 14.0),
 (59, 69, 'Male', 'Hoodie', 'Clothing', 54, 'Missouri', 'M', 'Charcoal', 'Summer', 4.2, 'Yes', 'Free Shipping', 'Yes', 29, 'Venmo', 'Monthly', 'senior', 30.0),
 (60, 63, 'Male', 'Belt', 'Accessories', 79, 'Louisiana', 'L', 'Yellow', 'Spring', 4.6, 'Yes', 'Standard', 'Yes', 4, 'Debit Card', 'Weekly', 'senior', 7.0),
 (61, 50, 'Male', 'Sweater', 'Clothing', 37, 'Idaho', 'L', 'Brown', 'Summer', 4.0, 'Yes', 'Express', 'Yes', 17, 'Cash', 'Weekly', 'middle_aged', 7.0),
 (62, 55, 'Male', 'Scarf', 'Accessories', 68, 'Texas', 'M', 'Orange', 'Winter', 4.7, 'Yes', 'Store Pickup', 'Yes', 21, 'Credit Card', 'Every 3 Months', 'middle_aged', 90.0),
 (63, 30, 'Male', 'Sneakers', 'Footwear', 21, 'Mississippi', 'S', 'Magenta', 'Spring', 3.8, 'Yes', 'Free Shipping', 'Yes', 31, 'Credit Card', 'Fortnightly', 'young_adult', 14.0),
 (64, 33, 'Male', 'Sunglasses', 'Accessories', 79, 'Arizona', 'L', 'Lavender', 'Winter', 2.7, 'Yes', '2-Day Shipping', 'Yes', 43, 'Credit Card', 'Weekly', 'adult', 7.0),
 (65, 65, 'Male', 'Boots', 'Footwear', 83, 'Alabama', 'S', 'Green', 'Fall', 4.8, 'Yes', 'Standard', 'Yes', 18, 'Debit Card', 'Fortnightly', 'senior', 14.0),
 (66, 65, 'Male', 'Backpack', 'Accessories', 36, 'New Jersey', 'M', 'Purple', 'Spring', 4.8, 'Yes', '2-Day Shipping', 'Yes', 44, 'Venmo', 'Every 3 Months', 'senior', 90.0),
 (67, 31, 'Male', 'Blouse', 'Clothing', 94, 'Pennsylvania', 'S', 'Magenta', 'Winter', 4.7, 'Yes', '2-Day Shipping', 'Yes', 3, 'Venmo', 'Every 3 Months', 'young_adult', 90.0),
 (68, 45, 'Male', 'Coat', 'Outerwear', 33, 'Connecticut', 'L', 'Gray', 'Winter', 4.4, 'Yes', 'Store Pickup', 'Yes', 49, 'Debit Card', 'Monthly', 'middle_aged', 30.0),
 (69, 57, 'Male', 'Handbag', 'Accessories', 46, 'Utah', 'L', 'Silver', 'Summer', 3.9, 'Yes', 'Next Day Air', 'Yes', 21, 'Cash', 'Every 3 Months', 'middle_aged', 90.0),
 (70, 48, 'Male', 'Belt', 'Accessories', 70, 'Tennessee', 'S', 'Cyan', 'Summer', 4.4, 'Yes', 'Express', 'Yes', 5, 'Cash', 'Weekly', 'middle_aged', 7.0),
 (71, 22, 'Male', 'Belt', 'Accessories', 29, 'Alabama', 'M', 'Magenta', 'Fall', 4.2, 'Yes', 'Express', 'Yes', 32, 'Debit Card', 'Every 3 Months', 'young_adult', 90.0),
 (72, 36, 'Male', 'Dress', 'Clothing', 48, 'Virginia', 'L', 'Gold', 'Summer', 2.9, 'Yes', 'Express', 'Yes', 34, 'Bank Transfer', 'Annually', 'adult', None),
 (73, 18, 'Male', 'Dress', 'Clothing', 26, 'Georgia', 'M', 'Olive', 'Winter', 2.9, 'Yes', 'Store Pickup', 'Yes', 21, 'Bank Transfer', 'Every 3 Months', 'young_adult', 90.0),
 (74, 48, 'Male', 'Pants', 'Clothing', 85, 'Hawaii', 'M', 'Teal', 'Spring', 2.7, 'Yes', 'Free Shipping', 'Yes', 43, 'Bank Transfer', 'Bi-Weekly', 'middle_aged', None),
 (75, 49, 'Male', 'Gloves', 'Accessories', 58, 'Indiana', 'L', 'Violet', 'Spring', 4.5, 'Yes', 'Express', 'Yes', 3, 'Cash', 'Monthly', 'middle_aged', 30.0),
 (76, 64, 'Male', 'Scarf', 'Accessories', 85, 'Utah', 'M', 'Blue', 'Summer', 2.7, 'Yes', 'Free Shipping', 'Yes', 21, 'Credit Card', 'Annually', 'senior', None),
 (77, 50, 'Male', 'Hat', 'Accessories', 43, 'Delaware', 'S', 'Teal', 'Summer', 4.2, 'Yes', 'Free Shipping', 'Yes', 32, 'Venmo', 'Monthly', 'middle_aged', 30.0),
 (78, 22, 'Male', 'Dress', 'Clothing', 53, 'Delaware', 'L', 'Gold', 'Summer', 3.3, 'Yes', 'Next Day Air', 'Yes', 36, 'Debit Card', 'Fortnightly', 'young_adult', 14.0),
 (79, 50, 'Male', 'Skirt', 'Clothing', 91, 'Nebraska', 'M', 'Maroon', 'Spring', 4.7, 'Yes', 'Free Shipping', 'Yes', 50, 'Venmo', 'Fortnightly', 'middle_aged', 14.0),
 (80, 38, 'Male', 'Jacket', 'Outerwear', 96, 'Iowa', 'M', 'Olive', 'Winter', 2.6, 'Yes', '2-Day Shipping', 'Yes', 43, 'Bank Transfer', 'Every 3 Months', 'adult', 90.0),
 (81, 19, 'Male', 'Sandals', 'Footwear', 72, 'New York', 'XL', 'Blue', 'Summer', 3.8, 'Yes', 'Store Pickup', 'Yes', 24, 'Credit Card', 'Every 3 Months', 'young_adult', 90.0),
 (82, 67, 'Male', 'Shoes', 'Footwear', 96, 'Virginia', 'L', 'Maroon', 'Summer', 2.6, 'Yes', 'Express', 'Yes', 36, 'Credit Card', 'Every 3 Months', 'senior', 90.0),
 (83, 19, 'Male', 'Pants', 'Clothing', 28, 'Georgia', 'S', 'Olive', 'Spring', 4.0, 'Yes', '2-Day Shipping', 'Yes', 21, 'Credit Card', 'Every 3 Months', 'young_adult', 90.0),
 (84, 36, 'Male', 'Dress', 'Clothing', 40, 'Texas', 'M', 'Turquoise', 'Summer', 4.1, 'Yes', 'Standard', 'Yes', 34, 'Bank Transfer', 'Weekly', 'adult', 7.0),
 (85, 52, 'Male', 'Coat', 'Outerwear', 32, 'Arizona', 'S', 'Peach', 'Spring', 4.4, 'Yes', 'Standard', 'Yes', 42, 'Bank Transfer', 'Every 3 Months', 'middle_aged', 90.0),
 (86, 53, 'Male', 'Sunglasses', 'Accessories', 95, 'New Mexico', 'M', 'Charcoal', 'Winter', 4.5, 'Yes', 'Next Day Air', 'Yes', 2, 'Debit Card', 'Bi-Weekly', 'middle_aged', None),
 (87, 24, 'Male', 'Hoodie', 'Clothing', 41, 'Nevada', 'L', 'Pink', 'Spring', 3.7, 'Yes', '2-Day Shipping', 'Yes', 47, 'Cash', 'Bi-Weekly', 'young_adult', None),
 (88, 52, 'Male', 'Shoes', 'Footwear', 53, 'Ohio', 'M', 'Green', 'Fall', 3.7, 'Yes', '2-Day Shipping', 'Yes', 44, 'Debit Card', 'Fortnightly', 'middle_aged', 14.0),
 (89, 33, 'Male', 'T-shirt', 'Clothing', 47, 'Wyoming', 'M', 'Orange', 'Fall', 3.5, 'Yes', 'Free Shipping', 'Yes', 35, 'Credit Card', 'Monthly', 'adult', 30.0),
 (90, 47, 'Male', 'Jacket', 'Outerwear', 83, 'California', 'XL', 'Pink', 'Fall', 3.6, 'Yes', 'Next Day Air', 'Yes', 15, 'Cash', 'Quarterly', 'middle_aged', 90.0),
 (91, 25, 'Male', 'Hat', 'Accessories', 48, 'South Carolina', 'L', 'Violet', 'Summer', 2.9, 'Yes', 'Express', 'Yes', 29, 'Credit Card', 'Monthly', 'young_adult', 30.0),
 (92, 44, 'Male', 'Scarf', 'Accessories', 99, 'South Carolina', 'S', 'Green', 'Winter', 4.6, 'Yes', 'Standard', 'Yes', 18, 'Credit Card', 'Every 3 Months', 'adult', 90.0),
 (93, 61, 'Male', 'Jacket', 'Outerwear', 87, 'Texas', 'M', 'Olive', 'Winter', 4.4, 'Yes', '2-Day Shipping', 'Yes', 13, 'Venmo', 'Every 3 Months', 'senior', 90.0),
 (94, 37, 'Male', 'Sweater', 'Clothing', 62, 'Florida', 'M', 'Purple', 'Fall', 4.5, 'Yes', 'Standard', 'Yes', 46, 'Credit Card', 'Weekly', 'adult', 7.0),
 (95, 58, 'Male', 'Skirt', 'Clothing', 76, 'Nevada', 'S', 'Silver', 'Spring', 4.6, 'Yes', 'Free Shipping', 'Yes', 28, 'Credit Card', 'Weekly', 'senior', 7.0),
 (96, 37, 'Male', 'Sneakers', 'Footwear', 100, 'Missouri', 'L', 'Pink', 'Fall', 3.8, 'Yes', 'Free Shipping', 'Yes', 48, 'PayPal', 'Monthly', 'adult', 30.0),
 (97, 32, 'Male', 'Gloves', 'Accessories', 73, 'Delaware', 'S', 'Gold', 'Spring', 3.8, 'Yes', 'Express', 'Yes', 43, 'Venmo', 'Every 3 Months', 'adult', 90.0),
 (98, 21, 'Male', 'Shoes', 'Footwear', 92, 'Virginia', 'M', 'Teal', 'Winter', 4.8, 'Yes', 'Store Pickup', 'Yes', 37, 'Cash', 'Annually', 'young_adult', None),
 (99, 20, 'Male', 'Jeans', 'Clothing', 67, 'New York', 'XL', 'Teal', 'Spring', 2.6, 'Yes', 'Next Day Air', 'Yes', 20, 'Bank Transfer', 'Annually', 'young_adult', None),
 (100, 26, 'Male', 'Hoodie', 'Clothing', 40, 'Missouri', 'XL', 'Indigo', 'Summer', 3.7, 'Yes', 'Express', 'Yes', 33, 'Debit Card', 'Quarterly', 'young_adult', 90.0),
 (101, 62, 'Male', 'Sunglasses', 'Accessories', 98, 'South Dakota', 'M', 'Maroon', 'Fall', 2.7, 'Yes', 'Express', 'Yes', 31, 'Cash', 'Fortnightly', 'senior', 14.0),
 (102, 27, 'Male', 'Coat', 'Outerwear', 85, 'North Dakota', 'XL', 'White', 'Spring', 4.6, 'Yes', 'Express', 'Yes', 50, 'Credit Card', 'Bi-Weekly', 'young_adult', None),
 (103, 51, 'Male', 'Socks', 'Clothing', 67, 'Oklahoma', 'L', 'Violet', 'Winter', 4.8, 'Yes', 'Next Day Air', 'Yes', 35, 'Credit Card', 'Quarterly', 'middle_aged', 90.0),
 (104, 54, 'Male', 'Boots', 'Footwear', 89, 'West Virginia', 'L', 'Red', 'Winter', 4.0, 'Yes', 'Next Day Air', 'Yes', 22, 'Venmo', 'Bi-Weekly', 'middle_aged', None),
 (105, 55, 'Male', 'Sunglasses', 'Accessories', 24, 'New Hampshire', 'L', 'Pink', 'Spring', 4.4, 'Yes', '2-Day Shipping', 'Yes', 1, 'PayPal', 'Monthly', 'middle_aged', 30.0),
 (106, 69, 'Male', 'Backpack', 'Accessories', 96, 'New York', 'M', 'Charcoal', 'Fall', 3.6, 'Yes', 'Next Day Air', 'Yes', 4, 'Bank Transfer', 'Annually', 'senior', None),
 (107, 64, 'Male', 'Jacket', 'Outerwear', 35, 'Minnesota', 'L', 'White', 'Summer', 3.7, 'Yes', 'Standard', 'Yes', 31, 'Credit Card', 'Monthly', 'senior', 30.0),
 (108, 28, 'Male', 'Sneakers', 'Footwear', 67, 'Maryland', 'L', 'Olive', 'Winter', 3.1, 'Yes', 'Next Day Air', 'Yes', 46, 'PayPal', 'Fortnightly', 'young_adult', 14.0),
 (109, 70, 'Male', 'Socks', 'Clothing', 79, 'Montana', 'L', 'Purple', 'Spring', 3.4, 'Yes', 'Next Day Air', 'Yes', 32, 'Bank Transfer', 'Bi-Weekly', 'senior', None),
 (110, 58, 'Male', 'T-shirt', 'Clothing', 85, 'Alabama', 'M', 'Violet', 'Spring', 2.6, 'Yes', 'Next Day Air', 'Yes', 43, 'Bank Transfer', 'Fortnightly', 'senior', 14.0),
 (111, 56, 'Male', 'Backpack', 'Accessories', 26, 'New York', 'M', 'Black', 'Summer', 4.0, 'Yes', 'Standard', 'Yes', 26, 'Venmo', 'Fortnightly', 'middle_aged', 14.0),
 (112, 26, 'Male', 'Belt', 'Accessories', 75, 'Massachusetts', 'L', 'Purple', 'Summer', 5.0, 'Yes', 'Free Shipping', 'Yes', 9, 'Credit Card', 'Annually', 'young_adult', None),
 (113, 37, 'Male', 'Gloves', 'Accessories', 65, 'Florida', 'M', 'Red', 'Spring', 4.3, 'Yes', 'Free Shipping', 'Yes', 28, 'PayPal', 'Bi-Weekly', 'adult', None),
 (114, 44, 'Male', 'Hat', 'Accessories', 54, 'New Jersey', 'L', 'Maroon', 'Winter', 3.1, 'Yes', 'Next Day Air', 'Yes', 20, 'PayPal', 'Quarterly', 'adult', 90.0),
 (115, 70, 'Male', 'Coat', 'Outerwear', 95, 'Massachusetts', 'S', 'Blue', 'Summer', 3.7, 'Yes', 'Store Pickup', 'Yes', 9, 'Cash', 'Weekly', 'senior', 7.0),
 (116, 53, 'Male', 'Skirt', 'Clothing', 94, 'Wyoming', 'M', 'Gray', 'Spring', 3.8, 'Yes', 'Standard', 'Yes', 48, 'Debit Card', 'Every 3 Months', 'middle_aged', 90.0),
 (117, 55, 'Male', 'Shoes', 'Footwear', 86, 'Virginia', 'S', 'Blue', 'Spring', 3.4, 'Yes', 'Free Shipping', 'Yes', 12, 'Venmo', 'Annually', 'middle_aged', None),
 (118, 50, 'Male', 'Sandals', 'Footwear', 32, 'South Dakota', 'L', 'Yellow', 'Summer', 4.6, 'Yes', 'Express', 'Yes', 29, 'Cash', 'Fortnightly', 'middle_aged', 14.0),
 (119, 50, 'Male', 'Sweater', 'Clothing', 45, 'Kentucky', 'L', 'Orange', 'Fall', 4.8, 'Yes', '2-Day Shipping', 'Yes', 27, 'Cash', 'Bi-Weekly', 'middle_aged', None),
 (120, 38, 'Male', 'Coat', 'Outerwear', 76, 'Wyoming', 'M', 'Orange', 'Fall', 4.3, 'Yes', 'Express', 'Yes', 44, 'Cash', 'Annually', 'adult', None),
 (121, 64, 'Male', 'Hat', 'Accessories', 84, 'West Virginia', 'L', 'Red', 'Summer', 4.0, 'Yes', 'Express', 'Yes', 32, 'Bank Transfer', 'Annually', 'senior', None),

In [27]:
%%sql
select gender ,sum(purchase_amount) as revenue 
from customer_data
group by gender;
#total revenue generated bt make vs female customers

 * mysql+pymysql://root:***@localhost:3306/sys
2 rows affected.
0 rows affected.

[]

In [28]:
%%sql
show tables;

 * mysql+pymysql://root:***@localhost:3306/sys
1 rows affected.

[('customer_data',)]

In [29]:
%%sql
show databases;

 * mysql+pymysql://root:***@localhost:3306/sys
9 rows affected.

[('autotrack360',),
 ('customer_behaviour',),
 ('information_schema',),
 ('mysql',),
 ('performance_schema',),
 ('sakila',),
 ('sql_lessons',),
 ('sys',),
 ('world',)]

In [30]:
%%sql
use customer_behaviour;

 * mysql+pymysql://root:***@localhost:3306/sys
0 rows affected.

[]

In [31]:
%%sql
select customer_id,purchase_amount
from customer_data
where discount_applied="Yes" 
and purchase_amount>=(select avg(purchase_amount) from customer_data)
#customers used a discount but still spent more than the average purchase amount

 * mysql+pymysql://root:***@localhost:3306/sys
839 rows affected.

[(2, 64),
 (3, 73),
 (4, 90),
 (7, 85),
 (9, 97),
 (12, 68),
 (13, 72),
 (16, 81),
 (20, 90),
 (22, 62),
 (24, 88),
 (29, 94),
 (32, 79),
 (33, 67),
 (35, 91),
 (37, 69),
 (40, 60),
 (41, 76),
 (43, 100),
 (44, 69),
 (55, 94),
 (57, 73),
 (58, 64),
 (60, 79),
 (62, 68),
 (64, 79),
 (65, 83),
 (67, 94),
 (70, 70),
 (74, 85),
 (76, 85),
 (79, 91),
 (80, 96),
 (81, 72),
 (82, 96),
 (86, 95),
 (90, 83),
 (92, 99),
 (93, 87),
 (94, 62),
 (95, 76),
 (96, 100),
 (97, 73),
 (98, 92),
 (99, 67),
 (101, 98),
 (102, 85),
 (103, 67),
 (104, 89),
 (106, 96),
 (108, 67),
 (109, 79),
 (110, 85),
 (112, 75),
 (113, 65),
 (115, 95),
 (116, 94),
 (117, 86),
 (120, 76),
 (121, 84),
 (122, 72),
 (124, 89),
 (125, 86),
 (128, 89),
 (130, 67),
 (134, 65),
 (135, 94),
 (136, 81),
 (137, 86),
 (140, 95),
 (146, 95),
 (148, 64),
 (149, 90),
 (150, 76),
 (151, 96),
 (153, 85),
 (155, 98),
 (156, 77),
 (158, 68),
 (159, 73),
 (163, 74),
 (164, 67),
 (165, 65),
 (166, 60),
 (169, 80),
 (173, 67),
 (176, 86),
 (177, 81),
 (181, 81),
 (182, 61),
 (183, 96),
 (188, 94),
 (190, 82),
 (191, 70),
 (192, 76),
 (194, 100),
 (195, 94),
 (197, 88),
 (198, 78),
 (200, 73),
 (201, 61),
 (205, 100),
 (206, 64),
 (208, 91),
 (210, 97),
 (212, 92),
 (213, 84),
 (214, 93),
 (216, 64),
 (217, 61),
 (220, 88),
 (222, 68),
 (223, 94),
 (225, 83),
 (227, 74),
 (228, 90),
 (229, 79),
 (231, 88),
 (234, 83),
 (236, 89),
 (237, 68),
 (238, 90),
 (242, 88),
 (243, 85),
 (244, 100),
 (247, 86),
 (248, 66),
 (249, 100),
 (254, 73),
 (259, 74),
 (262, 77),
 (265, 78),
 (267, 75),
 (272, 69),
 (276, 85),
 (279, 95),
 (280, 69),
 (281, 69),
 (282, 61),
 (283, 94),
 (289, 62),
 (290, 85),
 (293, 99),
 (297, 74),
 (300, 80),
 (301, 98),
 (302, 95),
 (304, 60),
 (305, 84),
 (311, 85),
 (313, 89),
 (314, 77),
 (318, 82),
 (319, 67),
 (320, 74),
 (321, 72),
 (323, 95),
 (324, 78),
 (325, 82),
 (326, 70),
 (332, 98),
 (333, 86),
 (334, 64),
 (336, 85),
 (337, 81),
 (339, 79),
 (345, 71),
 (350, 87),
 (351, 68),
 (352, 90),
 (353, 71),
 (354, 64),
 (355, 76),
 (357, 80),
 (360, 74),
 (362, 96),
 (363, 64),
 (364, 88),
 (365, 88),
 (366, 88),
 (372, 83),
 (373, 85),
 (375, 78),
 (379, 62),
 (381, 69),
 (383, 76),
 (384, 77),
 (386, 93),
 (388, 93),
 (389, 82),
 (391, 71),
 (392, 86),
 (393, 82),
 (394, 65),
 (396, 65),
 (397, 88),
 (399, 67),
 (401, 66),
 (402, 91),
 (403, 78),
 (405, 93),
 (406, 74),
 (408, 76),
 (409, 66),
 (413, 74),
 (414, 99),
 (415, 88),
 (418, 81),
 (419, 73),
 (420, 91),
 (426, 87),
 (427, 71),
 (428, 91),
 (429, 64),
 (430, 94),
 (432, 76),
 (433, 86),
 (434, 92),
 (441, 89),
 (442, 81),
 (443, 69),
 (444, 67),
 (447, 74),
 (448, 82),
 (455, 97),
 (456, 100),
 (457, 96),
 (458, 99),
 (459, 91),
 (461, 65),
 (462, 93),
 (463, 81),
 (464, 81),
 (466, 88),
 (471, 63),
 (472, 72),
 (475, 76),
 (476, 66),
 (477, 90),
 (480, 84),
 (481, 88),
 (482, 88),
 (484, 73),
 (485, 73),
 (487, 63),
 (488, 68),
 (490, 85),
 (492, 69),
 (493, 62),
 (495, 68),
 (497, 63),
 (499, 78),
 (500, 99),
 (506, 63),
 (510, 80),
 (511, 87),
 (514, 65),
 (515, 62),
 (516, 67),
 (519, 100),
 (521, 84),
 (523, 88),
 (529, 88),
 (530, 84),
 (533, 76),
 (534, 60),
 (535, 72),
 (537, 84),
 (543, 79),
 (544, 98),
 (545, 64),
 (547, 74),
 (549, 64),
 (551, 62),
 (552, 78),
 (553, 94),
 (557, 90),
 (558, 60),
 (559, 77),
 (562, 65),
 (563, 62),
 (564, 99),
 (567, 93),
 (569, 88),
 (571, 99),
 (572, 76),
 (573, 97),
 (574, 68),
 (575, 79),
 (576, 86),
 (577, 68),
 (579, 90),
 (581, 80),
 (582, 100),
 (583, 77),
 (584, 78),
 (585, 94),
 (588, 86),
 (589, 60),
 (590, 70),
 (595, 83),
 (596, 77),
 (598, 69),
 (599, 66),
 (601, 63),
 (605, 92),
 (607, 90),
 (611, 72),
 (615, 85),
 (616, 100),
 (617, 72),
 (619, 94),
 (621, 89),
 (623, 63),
 (624, 70),
 (625, 87),
 (626, 79),
 (627, 79),
 (629, 85),
 (630, 90),
 (631, 94),
 (632, 68),
 (635, 60),
 (641, 88),
 (642, 78),
 (645, 93),
 (648, 70),
 (650, 93),
 (654, 68),
 (658, 80),
 (661, 79),
 (662, 68),
 (663, 98),
 (664, 83),
 (665, 83),
 (668, 76),
 (669, 85),
 (670, 89),
 (674, 66),
 (676, 86),
 (677, 60),
 (678, 62),
 (679, 74),
 (680, 95),
 (685, 82),
 (686, 71),
 (690, 91),
 (691, 68),
 (693, 95),
 (696, 67),
 (698, 63),
 (701, 79),
 (702, 90),
 (703, 71),
 (704, 87),
 (705, 66),
 (706, 90),
 (710, 79),
 (711, 91),
 (712, 60),
 (713, 81),
 (714, 90),
 (715, 70),
 (716, 63),
 (718, 90),
 (721, 62),
 (725, 79),
 (726, 61),
 (727, 78),
 (728, 97),
 (729, 78),
 (735, 69),
 (741, 69),
 (742, 79),
 (744, 84),
 (745, 66),
 (746, 92),
 (748, 74),
 (750, 71),
 (751, 95),
 (752, 72),
 (753, 85),
 (757, 99),
 (759, 71),
 (762, 91),
 (766, 99),
 (768, 77),
 (769, 95),
 (770, 100),
 (772, 68),
 (774, 84),
 (777, 60),
 (780, 94),
 (784, 65),
 (785, 72),
 (786, 62),
 (788, 85),
 (790, 84),
 (797, 78),
 (798, 82),
 (808, 89),
 (809, 96),
 (810, 81),
 (811, 83),
 (815, 62),
 (816, 84),
 (819, 91),
 (825, 94),
 (826, 94),
 (827, 94),
 (829, 62),
 (831, 76),
 (832, 63),
 (833, 80),
 (834, 68),
 (835, 89),
 (837, 90),
 (842, 88),
 (843, 87),
 (844, 80),
 (847, 72),
 (849, 73),
 (850, 61),
 (852, 86),
 (853, 60),
 (856, 76),
 (858, 60),
 (860, 73),
 (861, 87),
 (862, 100),
 (863, 84),
 (867, 69),
 (869, 83),
 (871, 66),
 (874, 77),
 (875, 65),
 (878, 65),
 (879, 89),
 (880, 76),
 (881, 75),
 (882, 61),
 (885, 91),
 (886, 99),
 (889, 77),
 (890, 84),
 (893, 64),
 (895, 60),
 (896, 69),
 (898, 91),
 (899, 70),
 (901, 98),
 (902, 68),
 (905, 99),
 (906, 68),
 (909, 99),
 (912, 74),
 (915, 67),
 (918, 64),
 (920, 82),
 (921, 81),
 (923, 60),
 (925, 78),
 (926, 88),
 (927, 63),
 (928, 78),
 (930, 94),
 (931, 78),
 (934, 84),
 (937, 84),
 (939, 97),
 (940, 89),
 (943, 91),
 (944, 63),
 (945, 97),
 (949, 90),
 (953, 71),
 (955, 74),
 (956, 75),
 (957, 99),
 (960, 99),
 (962, 72),
 (963, 64),
 (964, 63),
 (969, 67),
 (971, 66),
 (972, 67),
 (973, 61),
 (974, 75),
 (975, 90),
 (977, 90),
 (981, 98),
 (983, 62),
 (985, 78),
 (986, 80),
 (987, 96),
 (989, 84),
 (991, 63),
 (992, 97),
 (993, 99),
 (994, 90),
 (995, 68),
 (996, 80),
 (997, 91),
 (999, 90),
 (1002, 60),
 (1004, 68),
 (1005, 79),
 (1006, 94),
 (1007, 83),
 (1008, 62),
 (1009, 85),
 (1014, 69),
 (1015, 97),
 (1019, 70),
 (1020, 76),
 (1021, 95),
 (1024, 71),
 (1025, 66),
 (1026, 84),
 (1027, 95),
 (1028, 90),
 (1031, 89),
 (1036, 89),
 (1039, 74),
 (1043, 80),
 (1044, 76),
 (1046, 79),
 (1049, 77),
 (1051, 64),
 (1054, 70),
 (1055, 96),
 (1057, 64),
 (1062, 62),
 (1063, 75),
 (1067, 96),
 (1069, 94),
 (1070, 81),
 (1071, 75),
 (1072, 81),
 (1073, 92),
 (1074, 96),
 (1075, 71),
 (1077, 72),
 (1083, 85),
 (1084, 97),
 (1086, 85),
 (1087, 62),
 (1088, 71),
 (1090, 61),
 (1092, 80),
 (1099, 98),
 (1100, 73),
 (1102, 76),
 (1103, 83),
 (1106, 83),
 (1107, 96),
 (1108, 62),
 (1110, 97),
 (1111, 61),
 (1112, 66),
 (1113, 67),
 (1114, 80),
 (1117, 96),
 (1118, 77),
 (1119, 65),
 (1121, 84),
 (1123, 62),
 (1124, 67),
 (1126, 90),
 (1130, 65),
 (1132, 73),
 (1133, 98),
 (1135, 81),
 (1136, 90),
 (1137, 83),
 (1138, 91),
 (1143, 76),
 (1146, 89),
 (1149, 66),
 (1152, 86),
 (1155, 82),
 (1158, 66),
 (1159, 89),
 (1163, 92),
 (1165, 96),
 (1166, 64),
 (1168, 83),
 (1169, 91),
 (1170, 94),
 (1171, 62),
 (1173, 68),
 (1174, 76),
 (1176, 81),
 (1177, 83),
 (1182, 96),
 (1185, 73),
 (1186, 64),
 (1187, 68),
 (1188, 89),
 (1190, 97),
 (1192, 70),
 (1196, 95),
 (1197, 88),
 (1198, 92),
 (1200, 89),
 (1202, 61),
 (1204, 82),
 (1205, 94),
 (1206, 99),
 (1208, 90),
 (1209, 100),
 (1210, 62),
 (1211, 78),
 (1212, 94),
 (1213, 74),
 (1215, 81),
 (1218, 63),
 (1219, 79),
 (1221, 64),
 (1222, 69),
 (1223, 69),
 (1226, 97),
 (1227, 91),
 (1231, 80),
 (1232, 79),
 (1234, 73),
 (1235, 99),
 (1237, 68),
 (1238, 92),
 (1239, 77),
 (1241, 79),
 (1245, 76),
 (1247, 60),
 (1248, 99),
 (1252, 86),
 (1256, 68),
 (1258, 67),
 (1259, 87),
 (1260, 64),
 (1261, 93),
 (1263, 62),
 (1264, 70),
 (1265, 92),
 (1266, 79),
 (1268, 83),
 (1269, 88),
 (1271, 98),
 (1273, 80),
 (1275, 73),
 (1277, 68),
 (1278, 97),
 (1279, 98),
 (1281, 78),
 (1282, 81),
 (1283, 68),
 (1284, 94),
 (1285, 93),
 (1286, 99),
 (1289, 93),
 (1292, 68),
 (1293, 61),
 (1294, 74),
 (1295, 64),
 (1296, 60),
 (1298, 85),
 (1299, 81),
 (1301, 100),
 (1305, 63),
 (1312, 87),
 (1313, 79),
 (1315, 67),
 (1316, 75),
 (1319, 93),
 (1322, 84),
 (1323, 74),
 (1324, 62),
 (1325, 77),
 (1326, 73),
 (1329, 97),
 (1330, 63),
 (1331, 65),
 (1332, 91),
 (1333, 60),
 (1334, 69),
 (1337, 85),
 (1338, 86),
 (1341, 72),
 (1347, 91),
 (1348, 95),
 (1351, 71),
 (1353, 89),
 (1354, 83),
 (1356, 91),
 (1357, 61),
 (1358, 66),
 (1360, 68),
 (1364, 90),
 (1365, 75),
 (1366, 69),
 (1368, 63),
 (1370, 75),
 (1371, 67),
 (1372, 64),
 (1373, 61),
 (1375, 97),
 (1377, 65),
 (1380, 64),
 (1382, 86),
 (1385, 96),
 (1386, 64),
 (1388, 85),
 (1390, 72),
 (1398, 67),
 (1400, 81),
 (1406, 100),
 (1408, 61),
 (1411, 93),
 (1413, 100),
 (1414, 79),
 (1416, 90),
 (1419, 75),
 (1420, 75),
 (1422, 100),
 (1424, 60),
 (1428, 90),
 (1429, 97),
 (1432, 88),
 (1434, 60),
 (1435, 64),
 (1436, 95),
 (1437, 83),
 (1438, 97),
 (1441, 76),
 (1443, 92),
 (1449, 95),
 (1454, 93),
 (1456, 79),
 (1457, 100),
 (1461, 85),
 (1462, 95),
 (1463, 90),
 (1465, 92),
 (1466, 72),
 (1467, 71),
 (1470, 98),
 (1472, 71),
 (1474, 63),
 (1475, 72),
 (1476, 61),
 (1480, 100),
 (1481, 74),
 (1483, 67),
 (1484, 61),
 (1487, 73),
 (1495, 76),
 (1497, 98),
 (1500, 85),
 (1501, 69),
 (1503, 66),
 (1505, 80),
 (1508, 86),
 (1509, 84),
 (1512, 91),
 (1515, 90),
 (1516, 93),
 (1517, 68),
 (1519, 73),
 (1520, 73),
 (1521, 66),
 (1523, 72),
 (1524, 88),
 (1525, 76),
 (1528, 75),
 (1529, 75),
 (1530, 63),
 (1532, 83),
 (1535, 66),
 (1536, 74),
 (1537, 82),
 (1538, 89),
 (1539, 65),
 (1541, 95),
 (1542, 77),
 (1544, 89),
 (1559, 75),
 (1560, 94),
 (1561, 84),
 (1563, 75),
 (1566, 93),
 (1567, 99),
 (1569, 76),
 (1570, 63),
 (1572, 88),
 (1573, 92),
 (1577, 75),
 (1579, 97),
 (1580, 80),
 (1581, 71),
 (1582, 77),
 (1584, 92),
 (1585, 95),
 (1587, 77),
 (1588, 99),
 (1590, 72),
 (1591, 80),
 (1592, 100),
 (1593, 83),
 (1594, 95),
 (1599, 85),
 (1604, 98),
 (1605, 92),
 (1608, 72),
 (1610, 93),
 (1613, 68),
 (1616, 62),
 (1618, 64),
 (1619, 72),
 (1620, 78),
 (1629, 64),
 (1630, 88),
 (1634, 80),
 (1640, 65),
 (1643, 70),
 (1644, 77),
 (1645, 90),
 (1647, 77),
 (1648, 78),
 (1649, 69),
 (1650, 63),
 (1652, 80),
 (1654, 93),
 (1656, 81),
 (1659, 66),
 (1662, 86),
 (1667, 64),
 (1671, 73),
 (1673, 73),
 (1674, 62),
 (1676, 90)]

In [32]:
%%sql
select item_purchased,round (avg(review_rating),2) as "average product rating"
from customer_data 
group by item_purchased
order by avg(review_rating) desc
limit 5;
#top 5 products with highest review rating

 * mysql+pymysql://root:***@localhost:3306/sys
5 rows affected.
0 rows affected.

[]

In [33]:
%%sql
select shipping_type,
round (avg(purchase_amount),2)
from customer_data
where shipping_type in ("Standard","Express")
group by shipping_type
#compare avg purchase amount between average and express shipping

 * mysql+pymysql://root:***@localhost:3306/sys
2 rows affected.

[('Express', Decimal('60.48')), ('Standard', Decimal('58.46'))]

In [34]:
%%sql
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount), 2) AS average_spend,
round(sum(purchase_amount), 2) AS total_revenue
from customer_data
group by subscription_status
order by total_revenue desc, average_spend desc;

 * mysql+pymysql://root:***@localhost:3306/sys
2 rows affected.

[('No', 2847, Decimal('59.87'), Decimal('170436')),
 ('Yes', 1053, Decimal('59.49'), Decimal('62645'))]

In [35]:
%%sql
select item_purchased,
round(sum(case when discount_applied="Yes" then 1 else 0 end )/count(*)*100,2) as discount_rate
from customer_data
group  by item_purchased
order by discount_rate desc
limit 5;

 * mysql+pymysql://root:***@localhost:3306/sys
5 rows affected.

[('Hat', Decimal('50.00')),
 ('Sneakers', Decimal('49.66')),
 ('Coat', Decimal('49.07')),
 ('Sweater', Decimal('48.17')),
 ('Pants', Decimal('47.37'))]

In [36]:
%%sql
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
    FROM customer_data
)

SELECT customer_segment, 
       COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

 * mysql+pymysql://root:***@localhost:3306/sys
3 rows affected.

[('Loyal', 3116), ('Returning', 701), ('New', 83)]

In [37]:
%%sql
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

 * mysql+pymysql://root:***@localhost:3306/sys
11 rows affected.

[(1, 'Accessories', 'Jewelry', 171),
 (2, 'Accessories', 'Sunglasses', 161),
 (3, 'Accessories', 'Belt', 161),
 (1, 'Clothing', 'Blouse', 171),
 (2, 'Clothing', 'Pants', 171),
 (3, 'Clothing', 'Shirt', 169),
 (1, 'Footwear', 'Sandals', 160),
 (2, 'Footwear', 'Shoes', 150),
 (3, 'Footwear', 'Sneakers', 145),
 (1, 'Outerwear', 'Jacket', 163),
 (2, 'Outerwear', 'Coat', 161)]

In [40]:
%%sql
select subscription_status,
count(customer_id) as repeat_buyers
from customer_data
where previous_purchases > 5
group by subscription_status;

 * mysql+pymysql://root:***@localhost:3306/sys
2 rows affected.

[('Yes', 958), ('No', 2518)]

In [42]:
%%sql
select age_group,
sum(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue desc;

 * mysql+pymysql://root:***@localhost:3306/sys
4 rows affected.

[('young_adult', Decimal('62143')),
 ('middle_aged', Decimal('59197')),
 ('adult', Decimal('55978')),
 ('senior', Decimal('55763'))]